/**/chassis_impedance:
  ros__parameters:
    # impedance control work loop rate [hz]
    rate_ros: 1000.0

    # keyboard monitor rate [hz]
    rate_teleop: 100.0

    # Isotropic SE(2) impedance gains [pos, yaw]
    impedance_kp: [500.0, 150.0]
    impedance_kd: [200.0, 15.0]
    impedance_force_limit: [50.0, 50.0]
    impedance_torque_limit: [50.0, 50.0]
    impedance_pos_threshold: 1.0
    impedance_yaw_threshold: 1.0

    # Maver X4 chassis geometry [m]
    chs_type: "maver_x4"
    chs_bias: 0.02
    chs_wheel_radius: 0.0625
    chs_track_width: 0.28
    chs_wheel_base: 0.424
